#! /bin/sh
### BEGIN INIT INFO
# Provides:          gerrit
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gerrit daemon service
# Description:       Starts, stops or restarts the Gerrit daemon. The
#                    daemon is used for code review and GIT repository
#                    management.
### END INIT INFO

# Author: Yubao Liu <yubao.liu@gmail.com>
#

real_script=/srv/gerrit/site/bin/gerrit.sh
[ -x $real_script ] && exec $real_script "$@"

