#!/bin/sh

# Update local /var/lib/misc/{passwd,group}.db from slapd.
# Sleep randomly to avoid network congestion and slapd's peak load.
#
# XXX: nss_updatedb always creates new db and replace old one, even
# when nothing changes, this harms disk...

sleep $(expr $(ip link | sum | awk '{print $1}') % 300)
/usr/sbin/nss_updatedb ldap > /dev/null

