#!/bin/bash

export LD_LIBRARY_PATH=`pwd`

ok_num=`grep -cw ok test_apdb.c`
mkdir for_test
cd for_test
result=`../test_apdb linuxapp 2>&1 |tee log | grep -cw ok`

if [ $ok_num -eq $result ]; then
    echo Passed.
else
    echo Failed, see ./for_test/log for details.
fi

