SharedLibrary('bbs', Split("""
    apdb.c
    board.c
    env.c
    util.c"""))

SharedLibrary('jail', ['jail.c'], LIBS=['dl'])

Program('boardd', 'boardd.c', LIBS=['bbs'], LIBPATH='.')

Program('test_apdb', 'test_apdb.c', LIBS=['bbs'], LIBPATH='.')


