DOC=beamer-warsaw-theme

all: $(DOC).tex
	xelatex $(DOC)
	xelatex $(DOC)

clean:
	-rm -f $(DOC).aux
	-rm -f $(DOC).log
	-rm -f $(DOC).nav
	-rm -f $(DOC).out
	-rm -f $(DOC).out.bak
	-rm -f $(DOC).pdf
	-rm -f $(DOC).snm
	-rm -f $(DOC).toc

