#!/bin/zsh

if [ x"$HOME" = x ]; then
    export HOME=$(cd ~; pwd)
fi

if [ x"$HOSTNAME" = x ]; then
    export HOSTNAME=$(hostname)
fi

export EMAIL="linuxemacs@gmail.com"
export FULLNAME="Jiang Jiang"

# less options
LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"

