#!/bin/zsh

CPU_MODULE=$(grep -m1 '^model name' /proc/cpuinfo | cut -d : -f 2)
case "$CPU_MODULE" in
    *Opteron*)      export CPU_CFLAGS="-mtune=opteron"  ;;
    *Pentrium*M)    export CPU_CFLAGS="-mtune=pentium-m";;
    *Core*2*)       export CPU_CFLAGS="-mtune=core2"    ;;
    *)              export CPU_CFLAGS=""                ;;
esac
export CFLAGS="$CPU_CFLAGS -O2 -g -Wall"
export CXXFLAGS="$CFLAGS"

# --- ccache ---
CCACHE_BIN_DIR=/usr/lib/ccache
MY_CCACHE_DIR=~/.ccache

if [ -d /usr/lib/ccache/ ] && ( echo $PATH | grep -v -q "$CCACHE_BIN_DIR" ); then
    export PATH=$CCACHE_BIN_DIR:$PATH
fi

if [ -L ${MY_CCACHE_DIR} ]; then
    MY_CCACHE_DIR=$(readlink ${MY_CCACHE_DIR})
fi

if [ -d ${MY_CCACHE_DIR} ] && [ -w ${MY_CCACHE_DIR} ]; then
    export CCACHE_BIN_DIR=${MY_CCACHE_DIR}
fi

