all: beamer-warsaw-theme.tex
	pdflatex beamer-warsaw-theme
	gbk2uni beamer-warsaw-theme.out
	pdflatex beamer-warsaw-theme

clean:
	-rm beamer-warsaw-theme.aux
	-rm beamer-warsaw-theme.log
	-rm beamer-warsaw-theme.nav
	-rm beamer-warsaw-theme.out
	-rm beamer-warsaw-theme.out.bak
	-rm beamer-warsaw-theme.pdf
	-rm beamer-warsaw-theme.snm
	-rm beamer-warsaw-theme.toc

