#!perl
#
# Purpose:
#   Copy to CLIPBOARD selection if some text is being selected,
#   paste from CLIPBOARD selection if no text is being selected.
#
# References:
#   `man urxvtperl`
#   http://wiki.archlinux.org/index.php/Rxvt-unicode
#
# Try with rxvt --perl-lib . -pe clipboard
#
#   Liu Yubao <yubao.liu@gmail.com>, 2010-09-16

#use Data::Dumper;
    #open my $fh, ">>/tmp/aa";
    #print $fh Dumper($self, $event);
    #close $fh;

    # No modifier pressed
    #$self->tt_write("# " . (sprintf "%b %b ", urxvt::AnyModifier, $event->{state}));
    #$self->tt_write("# button=" . $event->{button} . " ");

sub on_button_release {
    my ($self, $event) = @_;


    if ( $event->{state} == (urxvt::Mod2Mask | urxvt::Button3Mask) ) {
        my $selection = $self->selection;

        if ( length($selection) > 0 ) {
            $self->tt_write("# copy");

            open my $fh, "| xsel -ib" or return;
            print $fh, $selection;
            close $fh;

        } else {
            $self->tt_write("# paste");

            open my $fh, "xsel -ob |" or return;
            binmode $fh;
            {
                local $/;
                $self->tt_write($_) if <$fh>;
            }
            close $fh;
        }

        return 1;
    }

    return;
}

