#!/usr/bin/expect --

if { 0 == $argc } {
    spawn -noecho ssh newsmth
} else {
    eval spawn -noecho $argv
    #eval [linsert $argv 0 spawn -noecho]

    # for tcl >=8.5
    #spawn -noecho {*}$argv
}

expect_background eof {     # avoid nasty error when the spawned process exits
    exit
}

interact {
    timeout  60 {send "\x00"}
}

