#!/bin/sh
#
# Purpose:
#   cache result of find command to avoid heavy load on the disk I/O.
#
# Usage:
#   change your PATH temporarily to use find instead of /usr/bin/find,
#   delete corresponding file under $CACHE if you add or delete some
#   files.
#
# Author:
#   yubao.liu@gmail.com
#
# License:
#   BSDL
#
# ChangeLog:
#   2009-03-17  Liu Yubao
#       * initial version
#       * don't cache output of find if it goes wrong
#       * use ed instead of sed, suggested by Invader@newsmth
#       * record return value, keep cache (conflict with second change above)
#

CACHE="$HOME/.find-cache"

cwd="$PWD"
args="$*"
md5sum=`echo "$cwd $args" | md5sum | cut -c -32`
file="$CACHE/$md5sum"

[ -e "$CACHE" ] || mkdir -p "$CACHE"

if [ -f "$file" ]; then
    # The first line is cwd and args.
    echo '2,$-1p' | ed -s "$file"
    return `tail -1 "$file"`
else
    echo "command: $cwd $args" > "$file"
    # { /usr/bin/find "$@" || rm "$file"; } | tee -a "$file"
    { /usr/bin/find "$@" ; retval=$?; } | tee -a "$file"
    echo $retval >> "$file"
fi

